/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.Menu.FoodDetails;
import Business.Menu.MenuDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author garima
 */
public class ViewFoodItemJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFoodItemJPanel
     */
    JFileChooser chooser;
    File file;
    BufferedImage image;
    private JPanel container;
    private FoodDetails foodItem;
    private MenuDirectory menuDirectory;
    
    public ViewFoodItemJPanel(JPanel container,FoodDetails foodItem, MenuDirectory menuDirectory) {
        initComponents();
        this.container = container;
        this.foodItem = foodItem;
        this.menuDirectory = menuDirectory;
        itemNameTextField.setText(foodItem.getFoodItemName());
        itemDescriptionTextField.setText(foodItem.getFoodDescription());
        itemPriceTextField.setText(String.valueOf(foodItem.getFoodPrice()));
        itemIdTextField.setText(foodItem.getFoodItemId());
        itemPhoto.setIcon(new ImageIcon(foodItem.getFoodPhoto()));
        itemNameTextField.setEditable(false);
        itemDescriptionTextField.setEditable(false);
        itemPriceTextField.setEditable(false);
        itemIdTextField.setEditable(false);
        changeImgBtn.setVisible(false);
        image = foodItem.getFoodPhoto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        itemPhoto = new javax.swing.JLabel();
        itemIdTextField = new javax.swing.JTextField();
        itemNameTextField = new javax.swing.JTextField();
        itemDescriptionTextField = new javax.swing.JTextField();
        itemPriceTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        changeImgBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("View/ Edit Food Item");

        itemPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        itemPhoto.setMaximumSize(new java.awt.Dimension(120, 120));
        itemPhoto.setMinimumSize(new java.awt.Dimension(120, 120));
        itemPhoto.setPreferredSize(new java.awt.Dimension(120, 120));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveBtn.setText("Save Changes");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        changeImgBtn.setText("Choose");
        changeImgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeImgBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeImgBtn)
                            .addComponent(jButton1))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(itemIdTextField)
                                .addComponent(itemNameTextField)
                                .addComponent(itemDescriptionTextField)
                                .addComponent(itemPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1)))
                .addContainerGap(562, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itemIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(itemPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeImgBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(saveBtn))
                .addContainerGap(363, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String foodId = itemIdTextField.getText();
        String fname = itemNameTextField.getText();
        String fdescription = itemDescriptionTextField.getText();
        Double foodPrice = 0.0;
        try{
            foodPrice  = Double.parseDouble(itemPriceTextField.getText());
        } catch(NumberFormatException exception){
            JOptionPane.showMessageDialog(null, "Please enter valid price");
        }
       
        if(foodId.isEmpty() || fname.isEmpty() || fdescription.isEmpty() || foodPrice == 0.0 || image == null){
            JOptionPane.showMessageDialog(null, "Please enter all details correctly");
        }
        else{
            menuDirectory.updateFoodItem(foodItem.getFoodItemId(),fname,fdescription,foodPrice,image);
            itemNameTextField.setEditable(false);
            itemDescriptionTextField.setEditable(false);
            itemPriceTextField.setEditable(false);
            itemIdTextField.setEditable(false);
            changeImgBtn.setVisible(false);
            JOptionPane.showMessageDialog(null, "Food Item updated succesfully!");
            itemPhoto.setIcon(new ImageIcon(foodItem.getFoodPhoto()));
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        itemNameTextField.setEditable(true);
        itemDescriptionTextField.setEditable(true);
        itemPriceTextField.setEditable(true);
        changeImgBtn.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void changeImgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeImgBtnActionPerformed
        // TODO add your handling code here:
        chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        file = chooser.getSelectedFile();
        try{
            image = ImageIO.read(file);
        } catch (IOException e){
            image = foodItem.getFoodPhoto();
        }
    }//GEN-LAST:event_changeImgBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] components = container.getComponents();
        Component component = components[components.length - 1];
        ManageMenuJPanel manageMenuJPanel = (ManageMenuJPanel) component;
        manageMenuJPanel.populate();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeImgBtn;
    private javax.swing.JTextField itemDescriptionTextField;
    private javax.swing.JTextField itemIdTextField;
    private javax.swing.JTextField itemNameTextField;
    private javax.swing.JLabel itemPhoto;
    private javax.swing.JTextField itemPriceTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
